server:
 port: 8081

 
spring:
 datasource:
   driverClassName: com.mysql.cj.jdbc.Driver
   url: jdbc:mysql://localhost:3306/microservices
   username: root
   password: Nilesh@1995
  
 jpa:
  hibernate:
   ddl-auto: update
  show-sql: true
   
 application:
   name: userservice
   
 config:
  import: optional:configserver:http://localhost:8085
  
 security:
  oauth2:
   resourceserver:
    jwt:
     issuer-uri: https://dev-74511303.okta.com/oauth2/default
   client:
    registration: 
     my-internal-client: 
      provider: okta
      authorization-grant-type: client_credentials
      scope: internal
      client-id: 0oacr3xoueIH8tzFW5d7
      client-secret: 7x4CiwKQ_rvCF41P7uZONm73IPRKQCT2zf7mai9xXvpOtKGn2puLdJuhxUrDDMR3
    
    provider: 
     okta: 
      issuer-uri: https://dev-74511303.okta.com/oauth2/default
 
# used to active different profiles 
# profiles:
#  active: prod
   
 
 
#eureka:
# instance:
#  prefer-ip-address: true
# client:
#  fetch-registry: true
#  register-with-eureka: true
#  service-url:
#   defaultZone: http://localhost:8761/eureka

management:
 health:
  circuitbreakers:
   enabled: true
   
 endpoints:
  web:
   exposure: 
    include: health
    
 endpoint:
  health:
   show-details: always 
   
resilience4j:
 circuitbreaker:
  instances: 
   ratingHotelBreaker: 
    registerHealthIndicator: true
    eventConsumerBufferSize: 10
    failureRateThreshold: 50
    minimumNumberOfCalls: 5
    automaticTransitionFromOpenToHalfOpenEnabled: true
    waitDurationInOpenState: 6s 
    permittedNumberOfcallsInHalfOpenState: 3
    slidingWindowSize: 10
    slidingWindowType: COUNT_BASED

 retry:
  instances:
   ratingHotelService:
    max-attempts: 3
    wait-duration: 3s
    
 ratelimiter:
  instances:
   userRateLimiter:
    limit-refresh-period: 2s
    limit-for-period: 1
    timeout-duration: 2s
    
    
okta:
 oauth2:
  issuer: https://dev-74511303.okta.com/oauth2/default
  audience: api://default
     

   